[package]
name = "unipept"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.6", features = ["derive"] }
smartstring = { version = "1.0" }
#uniprot = "0.6.0"
uniprot = { git = "https://github.com/althonos/uniprot.rs.git", rev = "02b23d0" }
